image: registry.csc.sibsutis.ru/ci/git-clang-format:latest

stages:
  - check-format
  - build

check-format:
  stage: check-format
  script:
    - make format

build:
  stage: build
  script:
    - make
